name: Nginx Verification

on:
  push:
    branches: [ main ]

jobs:
  check_nginx:
    name: Check Nginx
    runs-on: self-hosted

    steps:
      - name: Verify Nginx
        run: |
          which nginx && nginx -v || { echo "nginx is not exist"; exit 1; }
